apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::640168421395:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-jkSOktDe0fUQ
      username: system:node:{{EC2PrivateDNSName}}
    mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::640168421395:user/Suresh
      username: Suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-04T12:45:44Z"
  name: aws-auth
  namespace: kube-system
  uid: 2097f35c-8d80-45f1-b6ef-338de7ce0f06