apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: expense-trainee-role
  namespace: expense
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: expense-trainee-rolebinding
  namesapce: expense
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: expense-trainee-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: Suresh

