apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: expense-trainee-role
  namespace: expense
  labels:
    purpose: rbac
rules:
- apiGroup: [""]
  resource: ["pods", "deployments", "services"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: roleBinding
metadata:
  name: expense-trainee-rolebinding
  namesapce: expense
  labels:
    purpose: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: expense-trainee-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: suresh
